### PR TITLE
Ruby tool to interact with Arduino sketch

### PR DESCRIPTION
**Pull request by kivikakk**
Hi there! Thanks so much for writing this, I've been able to flash my RTD2660 with the help of the Arduino sketch.

I was hoping to use the .NET frontend, but it seems like Windows.Forms applications can't run on Mono on recent macOS versions. I wrote a Ruby script to talk to it instead. It has some cute loading spinners and generally works pretty well. Here's a sample session verifying the new flash I just wrote:

```console
$ ruby flash.rb verify new.bin                                                                                         
connecting ...                                                                                                                                                
* got timeout, incomplete read (wanted 7+1, got "" (0 bytes) so far), retrying 4 more times ...                                                               
* got timeout, incomplete read (wanted 7+1, got "" (0 bytes) so far), retrying 3 more times ...                                                               
connected!                                                                                                                                                    
verifying 262144 bytes in flash in 256 byte increments                                                                                                        
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] /   262,144                                                                
$
```

Some parts aren't quite as configurable as they need to be yet, but it's a solid start for anyone wanting to interact with this sketch who can't run a .NET application.

### CODE REVIEW

**Comment by floppes** [comment]
Thank you very much for your contribution! Please give me a few days for review, I am not familiar with Ruby ;)
Btw, from my experience simple WinForms run fine with Mono on Linux. Maybe `System.IO.Ports.SerialPort` is not supported.

**Comment by kivikakk** [comment]
Yes, I do believe they work fine on Linux, though I'm not sure about `SerialPort` either. Unfortunately, macOS Catalina (10.15) dropped support for 32-bit applications entirely, and Mono's WinForms support is only functional on the 32-bit arch on macOS (see https://github.com/mono/mono/issues/17301, https://github.com/mono/mono/issues/6701, etc.), so something like this is helpful for us on Macs (and perhaps Linux users who don't want to install Mono).

**Comment by floppes** [comment]
I used your Ruby tool today on Windows and Linux and it worked fine :)
I have just one change request: could you please make the serial port name an argument to the tool? This would make using it easier instead of having to edit the code manually.

**Comment by kivikakk** [comment]
Thanks, that was very much missing. Fixed! Here's the new usage:

```console
$ ruby flash.rb
usage:
  ruby flash.rb SERIAL dump
    dumps 4MiB of flash to 'flash-contents.bin'

  ruby flash.rb SERIAL write FILE [OFFSET LENGTH]
    writes FILE to flash. it should probably be a multiple of 4096 bytes long.
    if OFFSET and LENGTH specified, only write sectors containing bytes starting
    from OFFSET for LENGTH bytes

  ruby flash.rb SERIAL verify FILE
    verifies FILE in flash

Specify SERIAL as a filesystem device node representing the serial connection to
the RTD266xArduino device.  You may also specify baud rate with SERIAL:BAUD,
otherwise defaults to 115200.

example usage:
  ruby flash.rb /dev/cu.usbmodem3201 dump
    Dump 4MiB of flash on the device connected at /dev/cu.usbmodem3201 to
    flash-contents.bin.

  ruby flash.rb /dev/cu.usbserial-AH069ECE:9600 write firmware.bin
    Writes firmware.bin to the device connected at /dev/cu.usbserial-AH069ECE at
    9600 baud.
```

**Pull request merged**
